/* =================================================================
 * nsc_api.h  —  NSC Gateway API (included by both S and NS worlds)
 *
 * These functions are the ONLY legal NS->Secure entry points.
 * In Secure world : implemented with __attribute__((cmse_nonsecure_entry))
 *                   → placed in NSC region with SG as first instruction
 * In NS world     : resolved to veneer stubs via secure_implib.o
 *                   → call generates BLXNS at the call site
 *
 * Compiler guarantees on cmse_nonsecure_entry functions:
 *  1. SG instruction generated as function entry (hardware gateway check)
 *  2. Unused return registers zeroed before returning to NS
 *     (prevents Secure register values leaking to NS world)
 *  3. Function placed in .gnu.sgstubs section (NSC memory region)
 *
 * NS callback mechanism (reverse direction — Secure calls NS):
 *  NS registers a function pointer via S_RegisterNSCallback().
 *  Secure validates it points to NS memory (cmse_check_address_range).
 *  Secure stores it with cmse_nsfptr_create() (clears bit 0).
 *  Secure calls it via BLXNS (generated by cmse_nonsecure_call attribute).
 * ================================================================= */

#ifndef NSC_API_H
#define NSC_API_H

#include <stdint.h>

/* ----------------------------------------------------------------
 * NS->Secure gateways (callable from Non-secure world)
 * ---------------------------------------------------------------- */

/* Read the Secure world tick counter (read-only for NS) */
uint32_t S_GetSecureTick(void);

/* Write one byte into the Secure-managed shared buffer.
 * Returns 0 on success, -1 if buffer is full. */
int S_WriteSharedBuffer(uint8_t data);

/* Read a Secure status word (controlled view of Secure state) */
uint32_t S_GetSecureStatus(void);

/* ----------------------------------------------------------------
 * NS callback registration (NS->Secure to register, then Secure->NS)
 *
 * __attribute__((cmse_nonsecure_call)) on the typedef:
 *  - Tells the compiler this pointer refers to a Non-secure function
 *  - Any call through this pointer generates BLXNS (not BL/BLX)
 *  - Caller automatically transitions to NS state for the call
 * ---------------------------------------------------------------- */
typedef void (*ns_callback_fn_t)(uint32_t event_data)
    __attribute__((cmse_nonsecure_call));

/* Register a NS callback. Secure world will invoke it via BLXNS
 * to notify NS of events. Secure validates the pointer before storing. */
void S_RegisterNSCallback(ns_callback_fn_t callback);

/* ----------------------------------------------------------------
 * Internal (called from Secure C only, not from NS)
 * ---------------------------------------------------------------- */
void nsc_init(void);
void nsc_invoke_ns_callback(uint32_t event_data);

#endif /* NSC_API_H */
